# Listado oficial de rubros del ERP
LISTA_RUBROS = [
    "ACEITE", "ACONDICIONADOR", "ALGODON", 
    "APOSITOS", "BAÑO LIQUIDO", "CAMBIADOR", "CHUPETE", 
    "COLONIA", "CREMA", "CUCHARAS", "DESCONGESTIONADORES NASALES", 
    "ESPONJA", "HIGIENE BUCAL", "HISOPOS", "JABON", 
    "LECHE", "LIMPIEZA ROPA", "MAMADERA", "MOCHILA MATERNAL", "MORDILLOS", 
    "OLEO CALCAREO", "PAÑALES", "PAÑALES ADULTOS", "PLATOS", "PROTECTOR MAMARIO", 
    "SACALECHES", "SEGURIDAD", "SHAMPOO", "TALCO", 
    "TETINAS", "TIJERAS", "TOALLITAS FEMENINAS", 
    "TOALLITAS HUMEDAS", "VASOS"
]
